version: "3"

volumes:
  pacman-mysql:

networks:
  deezNuts:
    name: deezNuts
    external: true


services:
  mysql:
    restart: always
    image: mysql:8.0
    volumes:
      - pacman-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: robotics_inv
      MYSQL_TCP_PORT: 5200
    ports:
      - 5200:5200
    networks:
      - deezNuts

  pacman:
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - deezNuts
    links:
      - mysql:sql