version: "3"

volumes:
  pacman-data:
  pacman-mysql:


services:
  mysql:
    image: mysql:8.0
    volumes:
      - pacman-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: robotics_inv
    ports:
      - 3306:3306
    networks:
      default:
        ipv4_address: 172.20.0.10

  pacman:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - pacman-data:/pac
    networks:
      default:
        ipv4_address: 172.20.0.11

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
