version: "3"

volumes:
  pacman-mysql:


services:
  mysql:
    restart: always
    network_mode: "host"
    image: mysql:8.0
    volumes:
      - pacman-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: robotics_inv
    ports:
      - 3306:3306

  pacman:
    restart: always
    network_mode: "host"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql